language: generic

env:
  global:
    - HUGO_VERSION=0.54.0
    - HUGO_PATH=$HOME/bin

    - PRD_BUCKET=galactic-meetup.duck-invaders.fr
    - STG_BUCKET=galactic-meetup.staging.duck-invaders.fr

    - PRD_CLOUDFRONT_ID=E3RC7LKJ5LAN7F
    - STG_CLOUDFRONT_ID=EG04QZBND6NP5

before_install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" -O /tmp/hugo.tar.gz

install:
  - tar -xzf /tmp/hugo.tar.gz -C "${HUGO_PATH}/"

script:
  - hugo

after_success:
  - |
    if [[ $TRAVIS_BRANCH = master ]]
    then
      pip install --user awscli
      aws configure set preview.cloudfront true

      if [[ $TRAVIS_PULL_REQUEST = false ]]
      then
        echo "deploy master to prod"
        CLOUDFRONT_ID=$PRD_CLOUDFRONT_ID
        BUCKET=$PRD_BUCKET
      else
        echo "deploy pull request to staging"
        CLOUDFRONT_ID=$STG_CLOUDFRONT_ID
        BUCKET=$STG_BUCKET
      fi

      aws s3 sync public/ "s3://${BUCKET}/" --delete
      aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_ID}" --paths "/*"
    fi
